### ISSUE TITLE
Additional Dependency

### ISSUE THREAD

**Issue by jlhumber** [realiii/autobox#31]
First round of parameter dependencies handled in #14, refer to [link](https://pro.arcgis.com/en/pro-app/latest/arcpy/geoprocessing_and_python/setting-script-tool-parameters.htm#GUID-3CB5FAF4-43DD-4C84-8AFE-08039A72B3E0)

```[tasklist]
### add parameters (basic stub)
- [x] Field Mappings ref #35
- [x] Geostatistical Value Table ref #35
- [x] Network Analyst Hierarchy Settings ref #35
- [x] Network Travel Mode ref #30
```

```[tasklist]
### extend existing implementation
- [x] Areal Unit - Feature Set / Record Set
- [x] Linear Unit - Feature Set / Record Set
- [x] Field - Feature Set / Record Set
- [x] SQL Expression - Feature Set / Record Set
```

```[tasklist]
### new implementation
- [x] Field Mappings - Table / Table View / Feature Class / Feature Layer / Raster Dataset / Raster Layer / Feature Set / Record Set
- [x] Geostatistical Value Table - Geostatistical Layer
- [x] Network Analyst Hierarchy Settings - Network Dataset
- [x] Network Travel Mode - Network Data Source / Network Dataset / Network Dataset Layer
```
