### ISSUE TITLE
Additional Parameters (in support of Filters and Dependency Parameters)

### ISSUE THREAD

**Issue by jlhumber** [realiii/autobox#32]
```[tasklist]
- [x] Feature Set
- [x] Record Set
- [x] Geostatistical Layer
- [x] Network Data Source
- [x] Network Dataset Layer
- [x] Network Dataset ref #11
- [x] Network Travel Mode ref #30
- [x] Time Unit ref #30
```
